version: "3.1"

services:
  mysql:
    image: "mysql:8.0.29"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234

volumes:
  mysql_data: